language: android
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
licenses:
- android-sdk-preview-license-c81a61d9
- android-sdk-license-.+
- google-gdk-license-.+
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script: "./gradlew test --stacktrace --no-daemon"
before_install:
- openssl aes-256-cbc -K $encrypted_faef0200f584_key -iv $encrypted_faef0200f584_iv
  -in fabric.properties.enc -out app/fabric.properties -d
- openssl aes-256-cbc -K $encrypted_faef0200f584_key -iv $encrypted_faef0200f584_iv
  -in stadroid-dev.jks.enc -out app/stadroid-dev.jks -d
- "./gradlew assembleRelease --stacktrace --no-daemon"
deploy:
  provider: script
  skip_cleanup: true
  script: "./gradlew crashlyticsUploadDistributionRelease"
  on:
    branch: master
