language: android
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
licenses:
- android-sdk-preview-license-c81a61d9
- android-sdk-license-.+
- google-gdk-license-.+
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script: "./gradlew clean assemble test --stacktrace --no-daemon"
before_install:
- openssl aes-256-cbc -K $encrypted_faef0200f584_key -iv $encrypted_faef0200f584_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar -C app/
- "./gradlew assembleRelease --stacktrace --no-daemon"
deploy:
  provider: script
  skip_cleanup: true
  script: "./gradlew crashlyticsUploadDistributionRelease"
  on:
    branch: master
notifications:
  slack:
    rooms:
      secure: GcR43VndC1e0pfFiBI4wWPkKydBmAvR6gmzzgaNxKN0aUvhQFduxWvNLRs7EboCOdht47RiV5M/y8VfMnCFOTmD1zrd0tS8NBFsq5enRXL8ndePtxXN2tRuRXOvJzIpvJKVJLIgNDYdntxSSBdwnXuG+3aIb4WA/pDNWVN+A4zYrYqZkZxs7YKPZa2hBBAXN72PKzuj4/ruhvAgzmtPCy1+6wIeW5PZtqa+EfRQidQviqY2Gkei2gMTkDuu/EyaWBl9l0QR48t95R7m8qCmH5/rxMOAvcZYZgnhoPS1czuM+XL2K5YqjTyuk+m0XGktEDZSAubGM/vikv5YdNjxWgtrvHskO3YeWxLqf+q7Dmn/wiFgFRB7ipV55YegQQr/uSM+x5R8CTZipbOFuY8mz0/i6UakRb7BELZYJcKvMQrbyhoZSamEh6qE9JUyGQeRcrcg0kek7xl/bsKTcqSlcVrBiE0NsSFclVow/SpbK86Ulb50elxyapETzr2dYar4nf4WtAv4tOP1ibPJW/fH4NoLGsbeFLjWKZvK/GLfAeA+diIdZEUhwogFF0cbN8dC3lW08/yxl9T3p1E8xYfhTK3iyonon3MfIA9SwY3exSQfjP0rgQKODuCFQQjkjDi+hbUQ4VaJPDrROf8nMG9KkmLaqF6bZ4DJxD/113rpVM/k=
