language: android
jdk:
- oraclejdk8
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
licenses:
- android-sdk-preview-license-c81a61d9
- android-sdk-license-.+
- google-gdk-license-.+
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script: "./gradlew clean assemble test --stacktrace --no-daemon"
before_install:
- openssl aes-256-cbc -K $encrypted_faef0200f584_key -iv $encrypted_faef0200f584_iv
  -in stadroid-dev.jks.enc -out app/stadroid-dev.jks -d
- "./gradlew assembleRelease --stacktrace --no-daemon"
deploy:
  provider: script
  skip_cleanup: true
  script: "./gradlew crashlyticsUploadDistributionRelease"
  on:
    branch: master
env:
  global:
  - secure: ZIbnYVZofdqm5w8gBUfp1+5XlQCgyHr+wHbDU+mEKZtylXpM+nqEBLyPzzHnBsArC7aJOEqii5coY+1LO1K3Q9H1gZBghqnozVQrRElrwRjy9hxgIk2zEcpwuWpJnotIN14h9raim6mrjmjZxeImsaFOsByxR4ZL/lOHEnQh6378mzplBuAcuSMMoA6Csv5FLDAxe3OXGTS4c4CzsVdVCn9238q/OQASzMBdaR33E8KN28T/OVAByT8Sidw8ycugn/v5ZJkS3pXM96JOJP6BGrw24V40byNRRkr2Lf3lAn/VchCtkAB/rZ5LaWgdUO53PsofdY/sJ9H0Snh0NNh8IgKnQ2y51+Rds7/xbbIBFQmErbPjaxXxeDcA8h8Qr/XDfPgJZRvkacy5iZrx60TqePDerfQAEpjoazdohgVsFtLiCqDUHuCT9ncuJvzx3cRO7jZJ3OrwcuPkP0mH3GWTcSTp8vTaOLZN7a4BdCRE+AYX5OsT3ifkyBgoScNYvKlte5LePtlb/5YguteZM1RQ+0vv8yKw6UWw04ig5dZKH80KbxlN5xV9OI1asQ8mSi//ZWTWllLy9zPP+nuF2pJMX6BBOH2HtYZA9zWsPEeJyolnwU56GHJ2ERcJcWFzcOaGJW8Im50n9xKdH+tmEGRCdkZ8TiOedjPT+IUHwbSjtVw=
  - secure: u+WCkjI6L66mVOyrElrB++d6rreDBJKE8k0GVSXoXpG26q+LmSakHgLpIHRYS1lhCEDNw0UAWLncH18x09JhlU5vz6wCaXV8CNMsVfFLX2kaX0tAGFBBGD8Hcn+4tVLYh9LOLuFO7fHFk+mz+cYOv2E1Se1jvDrNFcl2RblUH7FJK/nqHPmYpTNrYYA3eK+8xit12X7K0Td34Wy1KDwEORozAvUvRxe9DaLkG/cm321ZCAnPYTBz7p663w9RMaRKVVODYDjtwjxTePZ2OZNPLAjzGYVCae8LV8FQH2y3jWLauZYXmjxTDKnKcJEhwhw0AOzSPq7JWxcNtL73At6IShgsDjJ6+APaUKaIN20MUNVmAAE/ID5CXqjBM8k1ht2JpDOLXZD61YsxOVVXE0dNPZP/O/XlfWjfk906FIMq6nJNemb1I+BukpcZPTlSFS0fW37bbCmPwOskFevB4vyqUY2pLZ1c7A2gtBy3sKT1HhjMKQHMvXNV/k+zg4i4DOW+/v0sVEfpMAvikD1FnDqIvrJjv4aOH/ycKFxjpYMGB39Tse4U5qe2ITScPgg6P5PgBp73N10F1SvAvJygIoRl0AMRz4A6eM9+9d8+1fVVTElde7Wb/E9SGkN8tVqj9ur9v7Ac+AYU7LlpuXmQI7QN65i9exIkftKWr62kV81piog=
